name: Build CKAN + NetKAN

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        default: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ckan.exe and netkan.exe
        run: ./build --configuration=${{ inputs.configuration }}
      - name: Upload repack artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.configuration }}-repack-unsigned
          path: _build/repack/
          retention-days: 7
      - name: Upload out artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.configuration }}-out
          path: _build/out/
          retention-days: 1
      - name: Upload ckan.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: ckan.exe
          path: _build/repack/Release/ckan.exe
          retention-days: 7
        if: inputs.configuration == 'Release'
